export const projectReports = [
    {
      referenceNumber: "e5G6kKd",
      reportType: "Payment",
      description: "60% Down Payment",
      status: "paid",
      acknowledgedBy: "John Doe",
      acknowledgedAt: "2024-10-15 11:56:10",
      message: "Payment acknowledged and processed successfully.",
    },
    {
      referenceNumber: "proj-001",
      reportType: "Progress",
      description: "50% of the project completed",
      status: "in-progress",
      completedPercentage: 50,
      reportDate: "2024-10-18",
      message: "50% of the project is completed as of today. All tasks on track.",
    },
    {
      referenceNumber: "proj-002",
      reportType: "Progress",
      description: "70% of the electrical work is completed",
      status: "in-progress",
      completedPercentage: 70,
      reportDate: "2024-10-19",
      message: "70% of the electrical work is completed. Remaining tasks will finish in 2 days.",
    },
    {
      referenceNumber: "proj-003",
      reportType: "Deadline",
      description: "Project Deadline Approaching",
      status: "upcoming",
      dueDate: "2024-11-01",
      message: "The project is due to be completed by November 1st. Ensure timely finalization.",
    },
    {
      referenceNumber: "proj-004",
      reportType: "Progress",
      description: "100% of the project completed",
      status: "completed",
      completedPercentage: 100,
      reportDate: "2024-10-25",
      message: "The project is now fully completed. All deliverables have been met.",
    },
  ];
  